### ISSUE TITLE
use capture with classic AVRs

### ISSUE THREAD

**Issue by trimarco232** [aikopras/AP_DCC_library#3]
not an issue, just a discussion ...
capture is better then external interrupt, because it has filter, and it's interruption don't need to be served immediately
"classic" AVRs have capture input (too), generally by timer 1 ; it can input on different pins : 
- ICP1 pin
- AIN0 or AIN1 : analog comparator input, then timer 1 capture
- any analog (ADC) input, then ADMUX, then analog comparator, then timer 1 capture ; so, one can use the A6 or A7 input of a 328p (nano), and leave the external interrupt pin for other digital tasks

**Comment by aikopras** [comment]
Daar Trimarco232

Thanks for letting me know. I do not know all the details of the classic AVR’s, or at least I haven’t come across this possibility. Otherwise I might have tried that before. With the current price of classic AVRs it may not be too interesting anymore to spend much time on improvements in this direction (although I will later, once I’m home again, certainly take a look to see how simple / difficult it is). Nowadays I switch to the new AVR Dx processors, since they are extremely cheap and quite powerful. 

But again, thanks for the idea :-)

**Comment by trimarco232** [comment]
Hi Aiko,
thanks for answering,
I am using LGT8F328P boards, they are 99% compatible with classic AVRs, but faster (32MHz), and with a lot of improvements
I now new AVRs, but there is actually no aduino like boards at a decent price, in Eurasia
I managed to make the LGTs work (capture) while modifying the sup_isr_Mega.h ; it was (ugly made) but so simple to do that it worked immediately ; I am sure doing the same with AVR will be easy too
but I really don't now if it worth the effort to rework the library for that, not sure there is a demand for it ...
