### ISSUE TITLE
accCmd.setMyAddress problem with adresses

### ISSUE THREAD

**Issue by gorillale** [aikopras/AP_DCC_library#6]
Hello
I have used the command on setup:
```
uint8_t CV_ArraysUsed = 8;
uint16_t tAddr = 60;
accCmd.setMyAddress(tAddr / 4, (tAddr + CV_ArraysUsed - 1) / 4);
```

Then on DCC case MyAccessoryCmd the outputaddress  60  is not available.
61 to 67 are ok

What do i wrong?
Regards Andrew

**Comment by aikopras** [comment]
Hi Andrew

I assume you don't do anything wrong. What command station are you using?

Different command stations have different strategies for accessory addresses. Therefore there may be some offset in these addresses. I have included the myMaster attribute to compensate this for the command stations I own (and therefore could test). Did you set this attribute?

If you want to understand more regarding accessory commands, you can take a look at the comments at the start of the following file:

https://github.com/aikopras/AP_DCC_library/blob/main/src/sup_acc.cpp

**Comment by gorillale** [comment]
Hi, thank you for answer.
Actual i used iTrain with DCC-EX (MEGA) and BiDiB IF.
It ist each Address that has this problem.
I used now setAddr((addr/4)-1) actual, but i think is not the right way.
I sould use a range from 60 to 67 or 55 to 62.
Regards Andrew

**Comment by gorillale** [comment]
Is this the problem of switch decoder (1-4) ?
I used as accessory decoder with output-addresses and not as turnout decoder.
Into bit CV29 i have set to 0xE8

PS: ah i see the problem, you use 4er blocks, start with 1-4.
There is not a handle for decoders with outputaddress mode direct.

**Comment by aikopras** [comment]
From a distance it is hard to immediately see the problem. What I propose, is that you try from the examples the accessory monitor: [https://github.com/aikopras/AP_DCC_library/tree/main/examples/Accessory-Serial_monitor](https://github.com/aikopras/AP_DCC_library/tree/main/examples/Accessory-Serial_monitor)

With this tool you can test some accessory addresses, and see where the exact differences are.

And yes, the original idea was to use the range you are interested in, thus something like 60..66.

These numbers are decoder addresses (and not switch addresses), since that is how accessory CVs work. If I would have used switch addresses, I would have to make an internal mapping from switch to decoder addresses, that would likely make it more confusing. 

Interesting hardware you have. I would have loved to play with that, but I do not have that myself. I was not aware the iTrain could talk via BiDiB IF to DCC-EX. I thought DCC-EX was quite limited in its interfacing. Or do you use DDC-EX only as booster, and is the DCC signal generated by BiDiB IF?

**Comment by gorillale** [comment]
Thank you
the problem comes from the addr / 4 blocks.
Normal i calculate (((addr -1) / 4) + 1) then you have the Block 1 to 511.
On the decoder is this from 0-xxx on setMayAddress.
The other fail is that i calulated from 0 to 3 for the addresses, but into definition is this 1 to 4.
Than my correction of the addr-1 is correct.  

It's not nice that lower and upper overflow are detected, but this can be intercepted with the exact address output address. I use other libraries that allow the address to be set with real addresses (you can select this). I assume that you were using the first standard, block # and 1-4. It's all very confusing, the problem arose when converting other libraries to AP.

Thank you very much for your quick help.

**Comment by gorillale** [comment]
> Interesting hardware you have. I would have loved to play with that, but I do not have that myself. I was not aware the iTrain could talk via BiDiB IF to DCC-EX. I thought DCC-EX was quite limited in its interfacing. Or do you use DDC-EX only as booster, and is the DCC signal generated by BiDiB IF?

Used IF2, two Booster and many ReadyServo / Gbm16TS and selfmade decoders.
On first Test i use DCC-EX as testing on the developer system and programing.
After BiDiB for second test. DCC-Ex i use for testing locs etc... on my testbaoard, N and H0
The Layout use only BiDiB.
Regards

**Comment by aikopras** [comment]
> PS: ah i see the problem, you use 4er blocks, start with 1-4. There is not a handle for decoders with outputaddress mode direct.
 >It's not nice that lower and upper overflow are detected, but this can be intercepted with the exact address output address. I use other libraries that allow the address to be set with real addresses (you can select this). I assume that you were using the first standard, block # and 1-4. It's all very confusing, the problem arose when converting other libraries to AP.

I'm not sure if I understood your comments. 
Do you believe that I'm not following the (RCN) standards? If so, I have to correct this.
Or are you saying that I could make life for programmers easier, by giving an extra option? If so, I could add that.

Bye, Aiko
